import Foundation
import Observation

/// The signing key this build accepts updates from.
public enum UpdateTrust {
    /// The base64 Ed25519 public key, compiled in rather than stored in config.
    ///
    /// A key that lived beside the settings could be replaced by anything able to
    /// write that file, which would reduce the whole signature scheme to
    /// decoration. This is the same reasoning behind Sparkle's `SUPublicEDKey`.
    ///
    /// Generated by `Scripts/bud-update-keygen.sh`; the private half never leaves
    /// the machine that signs a release. Empty means this build cannot verify
    /// anything, and it will refuse to update rather than guess.
    public static let publicKey = "pCCEIK1Wvxf2TLeiweqtBIxp1enVe9+qwffLQzZl6vw="

    /// False for a build that was never given a key.
    ///
    /// Exposed so the UI can say so plainly instead of offering a button that
    /// could only ever refuse.
    public static var isConfigured: Bool {
        !publicKey.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }
}

/// The update lifecycle, as the UI sees it.
@MainActor
@Observable
public final class UpdateModel {
    /// One state, not a set of booleans. "Checking", "downloading" and "ready" are
    /// mutually exclusive, and a view that has to combine four flags to work out
    /// which one it is in eventually gets it wrong.
    public enum Phase: Sendable, Equatable {
        case idle
        case checking
        case upToDate(BudVersion)
        case available(UpdateManifest)
        case downloading(Double)
        case installing
        case installed(BudVersion)
        case failed(String)

        public var manifest: UpdateManifest? {
            if case .available(let manifest) = self { return manifest }
            return nil
        }

        public var isBusy: Bool {
            switch self {
            case .checking, .downloading, .installing: return true
            case .idle, .upToDate, .available, .installed, .failed: return false
            }
        }
    }

    public private(set) var phase: Phase = .idle
    public private(set) var lastChecked: Date?
    public let currentVersion: BudVersion?

    /// The feed the current `phase` came from.
    ///
    /// Kept so an install uses the same credential the check did. Rebuilding the
    /// feed at install time would re-read settings that may have changed in
    /// between, and a token that appeared after the check would not have been
    /// used to fetch the manifest it is now authorising.
    private var checkedFeed: UpdateFeed?
    /// Where the archive is actually fetched from, when the feed needed an
    /// authenticated route to reach it.
    private var checkedDownloadURL: URL?

    /// Ends the process so the relaunch helper can bring the new copy up.
    ///
    /// Non-optional, and never "do nothing". The helper waits for this pid to
    /// disappear and then opens the app; if nothing ever ends the process it
    /// waits out its two-minute bound and opens nothing, which looks exactly like
    /// a button that is broken — because it is. An updater that offers a Restart
    /// button has to be able to restart, so the ability is part of the type
    /// rather than a callback the app has to remember to supply.
    public var onQuit: @MainActor () -> Void

    public init(
        current: BudVersion? = BudVersion.current(),
        onQuit: (@MainActor () -> Void)? = nil
    ) {
        self.currentVersion = current
        // `exit` rather than `NSApp.terminate` as the fallback: this module does
        // not import AppKit, and a process that ends is what the helper needs.
        // The app replaces this with a clean `terminate` when it wires itself up.
        self.onQuit = onQuit ?? { exit(0) }
    }

    /// The app bundle to replace, or nil when this is not running from one.
    ///
    /// The self-test binary runs straight out of `.build`, and replacing the
    /// directory it lives in is meaningless — worse, it would look like it had
    /// worked. Everything that installs goes through this check.
    public var installedBundle: URL? {
        let bundle = Bundle.main.bundleURL
        return bundle.pathExtension == "app" ? bundle : nil
    }

    public var canInstall: Bool { installedBundle != nil && !phase.isBusy }

    // MARK: Checking

    public func check(feed: UpdateFeed, background: Bool = false) async {
        guard !phase.isBusy else { return }
        guard UpdateTrust.isConfigured else {
            if !background { phase = .failed(UpdateError.signingKeyMissing.localizedDescription) }
            return
        }
        guard let current = currentVersion else {
            if !background { phase = .failed(UpdateError.unknownCurrentVersion.localizedDescription) }
            return
        }

        phase = .checking
        checkedFeed = feed
        defer { lastChecked = Date() }
        do {
            switch try await UpdateChecker.check(feed: feed, current: current) {
            case .upToDate(let version):
                phase = .upToDate(version)
            case .available(let manifest, let downloadURL):
                checkedDownloadURL = downloadURL
                phase = .available(manifest)
            }
        } catch {
            // A background check that fails is not news. A laptop that is offline
            // should not open with an error nobody asked for; an explicit check
            // failing very much is news.
            phase = background ? .idle : .failed(message(for: error))
        }
    }

    // MARK: Installing

    public func install() async {
        guard case .available(let manifest) = phase else { return }
        guard let destination = installedBundle else {
            phase = .failed(
                UpdateError.installFailed("Bud is not running from an app bundle, so there is nothing to replace.")
                    .localizedDescription
            )
            return
        }

        phase = .downloading(0)
        do {
            let staged = try await UpdateInstaller.stage(
                manifest: manifest,
                destination: destination,
                token: checkedFeed?.token ?? "",
                downloadURL: checkedDownloadURL,
                progress: { [weak self] fraction in
                    Task { @MainActor in
                        guard let self, case .downloading = self.phase else { return }
                        self.phase = .downloading(fraction)
                    }
                }
            )
            phase = .installing
            try UpdateInstaller.apply(staged: staged.bundle, replacing: destination)
            phase = .installed(manifest.versionValue)
        } catch {
            phase = .failed(message(for: error))
        }
    }

    /// Hands off to a helper and quits, so the new copy starts.
    ///
    /// Quitting is part of the operation rather than a separate step the UI might
    /// forget: `open` on an app that is still running only brings the old one
    /// forward, so an update that installs and does not quit would look like one
    /// that did nothing at all.
    public func relaunch() {
        guard let destination = installedBundle else { return }
        do {
            try UpdateInstaller.relaunchAfterExit(app: destination)
            onQuit()
        } catch {
            phase = .failed(message(for: error))
        }
    }

    /// Back to a clean slate, so a dismissed error does not linger for ever.
    public func dismiss() {
        guard !phase.isBusy else { return }
        phase = .idle
    }

    private func message(for error: Error) -> String {
        (error as? LocalizedError)?.errorDescription ?? error.localizedDescription
    }
}
